name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  # pytroll dependencies
  - satpy
  - pyspectral
  - imageio
  - imageio-ffmpeg
  - cartopy
  - metpy
  - siphon
  - pip:
    - kubernetes
    - graphviz
